source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/hk01-digital/hk01-ios-uikit-spec.git'

platform :ios, '9.0'

target 'ChainableDemo' do
  use_frameworks!


  #pod 'DDKit/Chainable'

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
 pod 'SnapKit'


end
