# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/hk01-digital/hk01-ios-uikit-spec.git'

platform :ios, '9.0'

target 'DDRouterDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'DDKit/DDScan'

end
