source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
source 'https://github.com/hk01-digital/hk01-ios-uikit-spec.git'

platform :ios, '9.0'

target 'DDPhotoBrowserDemo' do
  use_frameworks!

pod 'Kingfisher', '4.9.0'
#pod 'DDKit/Hud'
#pod 'DDKit/PhotoBrowser'

end
